### ISSUE TITLE
Bulk count normalization

### ISSUE THREAD

**Issue by jhb1980** [wilsonlabgroup/scMappR#1]
Hello! Thanks for this tool, very much looking forward to exploring. 
For the `scMappR_and_pathway_analysis()` function, what normalization would be appropriate (/required) for the bulk RNA-seq counts: basic normalization for read depth (e.g. CPM), or further adjusted for gene length (e.g. FPKM)?

**Comment by DustinSokolowski** [comment]
Hey!

Thank you so much for you interest! `scMappR_and_pathway_analysis()` will not throw and error or warning for basic or depth + length adjusted normalization, thus allowing any method to work. Importantly, RNA-seq count data _should not_ be log2-normalized. Your inputted differential expressed genes _should_ be log2Fold-Changes.

 This being said, part of estimating cell-type proportions via RNA-seq deconvolution uses correlations between cell-type markers in bulk RNA-seq data and other genes in the bulk RNA-seq data. Using FPKM/RPKM will remove the possibility of genes being correlated based on gene-length, thus being potentially favorable to CPM.

Please let me know if you have any other questions!
Dustin

**Comment by jhb1980** [comment]
Thank you for clarifying!
